// <auto-generated />
using System;
using CoffeeShopLoyalty.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeeShopLoyalty.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260326204647_AddTipsToOrder")]
    partial class AddTipsToOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Кава та чай"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Напої б/а"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Кондитерка"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Випічка"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Хліба"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Круасани та мафіни"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Піца"
                        });
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BonusBalance")
                        .HasColumnType("numeric");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LoyaltyLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.LoyaltyTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PointsAdded")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PointsDeducted")
                        .HasColumnType("numeric");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.ToTable("LoyaltyTransactions");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CostPrice = 15m,
                            Description = "30 мл. Класична міцна кава",
                            IsAvailable = true,
                            Name = "Еспресо",
                            Price = 45m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CostPrice = 16m,
                            Description = "150 мл. Еспресо з додаванням гарячої води",
                            IsAvailable = true,
                            Name = "Американо",
                            Price = 50m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CostPrice = 25m,
                            Description = "250 мл. Еспресо зі збитим гарячим молоком",
                            IsAvailable = true,
                            Name = "Капучино",
                            Price = 65m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CostPrice = 30m,
                            Description = "350 мл. Багато молока та шот еспресо",
                            IsAvailable = true,
                            Name = "Лате",
                            Price = 75m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CostPrice = 35m,
                            Description = "200 мл. Подвійне еспресо та трохи збитого молока",
                            IsAvailable = true,
                            Name = "Флет Вайт",
                            Price = 80m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CostPrice = 45m,
                            Description = "300 мл. Кава на вершках з ванільним цукром",
                            IsAvailable = true,
                            Name = "Раф",
                            Price = 90m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CostPrice = 50m,
                            Description = "300 мл. Японський зелений чай з молоком",
                            IsAvailable = true,
                            Name = "Матча Лате",
                            Price = 110m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CostPrice = 10m,
                            Description = "400 мл. Заварний листовий чай",
                            IsAvailable = true,
                            Name = "Чай чорний",
                            Price = 55m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CostPrice = 10m,
                            Description = "400 мл. Заварний листовий чай з жасмином",
                            IsAvailable = true,
                            Name = "Чай зелений",
                            Price = 55m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            CostPrice = 25m,
                            Description = "300 мл. Натуральне какао на молоці",
                            IsAvailable = true,
                            Name = "Какао",
                            Price = 70m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            CostPrice = 30m,
                            Description = "400 мл. Лимон, м'ята, цукровий сироп, содова",
                            IsAvailable = true,
                            Name = "Лимонад Класичний",
                            Price = 85m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CostPrice = 35m,
                            Description = "400 мл. Лайм, свіжа м'ята, спрайт, лід",
                            IsAvailable = true,
                            Name = "Мохіто б/а",
                            Price = 95m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            CostPrice = 32m,
                            Description = "350 мл. Холодне молоко, еспресо, лід",
                            IsAvailable = true,
                            Name = "Айс Лате",
                            Price = 85m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            CostPrice = 40m,
                            Description = "300 мл. Тонік, подвійне еспресо, лід, лимон",
                            IsAvailable = true,
                            Name = "Еспресо Тонік",
                            Price = 100m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            CostPrice = 60m,
                            Description = "250 мл. 100% свіжовичавлений сік",
                            IsAvailable = true,
                            Name = "Фреш Апельсиновий",
                            Price = 120m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            CostPrice = 65m,
                            Description = "250 мл. 100% свіжовичавлений сік",
                            IsAvailable = true,
                            Name = "Фреш Грейпфрутовий",
                            Price = 130m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            CostPrice = 25m,
                            Description = "330 мл. Скляна пляшка",
                            IsAvailable = true,
                            Name = "Кока-Кола",
                            Price = 50m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            CostPrice = 18m,
                            Description = "500 мл. Негазована / Газована",
                            IsAvailable = true,
                            Name = "Вода Моршинська",
                            Price = 40m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            CostPrice = 50m,
                            Description = "330 мл. Ферментований напій (в асортименті)",
                            IsAvailable = true,
                            Name = "Комбуча",
                            Price = 90m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            CostPrice = 45m,
                            Description = "400 мл. Морозиво, молоко, збиті вершки",
                            IsAvailable = true,
                            Name = "Мілкшейк Ванільний",
                            Price = 110m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            CostPrice = 45m,
                            Description = "150 г. Класичний листковий торт з заварним кремом",
                            IsAvailable = true,
                            Name = "Торт Наполеон",
                            Price = 120m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            CostPrice = 55m,
                            Description = "160 г. Вершковий сир, пісочна основа",
                            IsAvailable = true,
                            Name = "Чизкейк Нью-Йорк",
                            Price = 140m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            CostPrice = 60m,
                            Description = "150 г. Савоярді, маскарпоне, кава",
                            IsAvailable = true,
                            Name = "Тірамісу",
                            Price = 135m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            CostPrice = 20m,
                            Description = "30 г. Мигдальне тістечко (різні смаки)",
                            IsAvailable = true,
                            Name = "Макарон",
                            Price = 55m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            CostPrice = 25m,
                            Description = "80 г. Заварне тісто, крем пломбір",
                            IsAvailable = true,
                            Name = "Еклер Ванільний",
                            Price = 80m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            CostPrice = 35m,
                            Description = "120 г. Шоколадний десерт з вологою серединкою",
                            IsAvailable = true,
                            Name = "Брауні",
                            Price = 95m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            CostPrice = 18m,
                            Description = "90 г. Бісквітна крихта, какао, ром",
                            IsAvailable = true,
                            Name = "Тістечко Картопля",
                            Price = 65m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            CostPrice = 40m,
                            Description = "140 г. Медові коржі зі сметанним кремом",
                            IsAvailable = true,
                            Name = "Медовик",
                            Price = 110m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            CostPrice = 35m,
                            Description = "150 г. Вершковий десерт з ягідним кюлі",
                            IsAvailable = true,
                            Name = "Панакота",
                            Price = 105m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            CostPrice = 45m,
                            Description = "110 г. Пісочне тісто, заварний крем, сезонні ягоди",
                            IsAvailable = true,
                            Name = "Тарталетка Ягідна",
                            Price = 125m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            CostPrice = 30m,
                            Description = "180 г. Булочка з корицею та крем-сиром",
                            IsAvailable = true,
                            Name = "Синнабон",
                            Price = 100m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            CostPrice = 15m,
                            Description = "100 г. Печений пиріжок зі свининою та яловичиною",
                            IsAvailable = true,
                            Name = "Пиріжок з м'ясом",
                            Price = 45m
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            CostPrice = 12m,
                            Description = "100 г. Печений пиріжок з солодкою вишнею",
                            IsAvailable = true,
                            Name = "Пиріжок з вишнею",
                            Price = 40m
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            CostPrice = 20m,
                            Description = "120 г. Молочна сосиска у листковому тісті",
                            IsAvailable = true,
                            Name = "Сосиска в тісті",
                            Price = 55m
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            CostPrice = 30m,
                            Description = "150 г. Листкове тісто, сир сулугуні",
                            IsAvailable = true,
                            Name = "Хачапурі з сиром",
                            Price = 85m
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            CostPrice = 60m,
                            Description = "200 г. Відкритий пиріг з лососем та шпинатом",
                            IsAvailable = true,
                            Name = "Кіш з лососем",
                            Price = 150m
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            CostPrice = 20m,
                            Description = "120 г. Листкове тісто з яблуком та корицею",
                            IsAvailable = true,
                            Name = "Слойка з яблуком",
                            Price = 60m
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            CostPrice = 22m,
                            Description = "110 г. Заварний крем та родзинки",
                            IsAvailable = true,
                            Name = "Равлик з родзинками",
                            Price = 65m
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            CostPrice = 15m,
                            Description = "130 г. Дріжджове тісто, багато маку",
                            IsAvailable = true,
                            Name = "Булочка з маком",
                            Price = 50m
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            CostPrice = 18m,
                            Description = "120 г. Класична ватрушка з домашнім сиром",
                            IsAvailable = true,
                            Name = "Ватрушка з сиром",
                            Price = 55m
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 5,
                            CostPrice = 15m,
                            Description = "300 г. Хрустка скоринка, пористий м'якуш",
                            IsAvailable = true,
                            Name = "Багет Французький",
                            Price = 60m
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 5,
                            CostPrice = 18m,
                            Description = "250 г. Класичний італійський хліб на заквасці",
                            IsAvailable = true,
                            Name = "Чіабата",
                            Price = 70m
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 5,
                            CostPrice = 20m,
                            Description = "400 г. Темний хліб на житній заквасці",
                            IsAvailable = true,
                            Name = "Хліб Житній",
                            Price = 65m
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            CostPrice = 22m,
                            Description = "350 г. З кмином та коріандром",
                            IsAvailable = true,
                            Name = "Бородінський",
                            Price = 75m
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 5,
                            CostPrice = 25m,
                            Description = "350 г. З додаванням гречаного борошна",
                            IsAvailable = true,
                            Name = "Гречаний хліб",
                            Price = 80m
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 5,
                            CostPrice = 15m,
                            Description = "450 г. Ідеально рівний для сендвічів",
                            IsAvailable = true,
                            Name = "Тостовий хліб",
                            Price = 55m
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 5,
                            CostPrice = 12m,
                            Description = "400 г. Класичний білий батон",
                            IsAvailable = true,
                            Name = "Батон Нарізний",
                            Price = 45m
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            CostPrice = 30m,
                            Description = "300 г. Італійський корж з чері та розмарином",
                            IsAvailable = true,
                            Name = "Фокача з томатами",
                            Price = 95m
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            CostPrice = 8m,
                            Description = "90 г. Бріош з кунжутом",
                            IsAvailable = true,
                            Name = "Булочка для бургера",
                            Price = 25m
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            CostPrice = 45m,
                            Description = "300 г. На основі рисового та кукурудзяного борошна",
                            IsAvailable = true,
                            Name = "Хліб безглютеновий",
                            Price = 120m
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 6,
                            CostPrice = 25m,
                            Description = "80 г. Справжній вершковий круасан на маслі 82%",
                            IsAvailable = true,
                            Name = "Круасан Класичний",
                            Price = 70m
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 6,
                            CostPrice = 35m,
                            Description = "110 г. З начинкою з бельгійського шоколаду",
                            IsAvailable = true,
                            Name = "Круасан Шоколадний",
                            Price = 95m
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 6,
                            CostPrice = 45m,
                            Description = "130 г. З франжипаном та мигдальними пластівцями",
                            IsAvailable = true,
                            Name = "Круасан з мигдалем",
                            Price = 120m
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 6,
                            CostPrice = 55m,
                            Description = "120 г. З фісташковим кремом",
                            IsAvailable = true,
                            Name = "Круасан Фісташковий",
                            Price = 135m
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 6,
                            CostPrice = 50m,
                            Description = "160 г. Ситний круасан з сиром чеддер та шинкою",
                            IsAvailable = true,
                            Name = "Круасан Шинка/Сир",
                            Price = 140m
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 6,
                            CostPrice = 80m,
                            Description = "170 г. Слабосолений лосось, крем-сир, рукола",
                            IsAvailable = true,
                            Name = "Круасан з лососем",
                            Price = 180m
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 6,
                            CostPrice = 25m,
                            Description = "110 г. Вологий кекс з шматочками шоколаду",
                            IsAvailable = true,
                            Name = "Мафін Шоколадний",
                            Price = 75m
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 6,
                            CostPrice = 28m,
                            Description = "110 г. Зі свіжою лохиною та чорницею",
                            IsAvailable = true,
                            Name = "Мафін Чорничний",
                            Price = 80m
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 6,
                            CostPrice = 20m,
                            Description = "110 г. Класичний кекс з ваніллю",
                            IsAvailable = true,
                            Name = "Мафін Ванільний",
                            Price = 65m
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 6,
                            CostPrice = 30m,
                            Description = "120 г. З тягучою солоною карамеллю всередині",
                            IsAvailable = true,
                            Name = "Мафін Солона Карамель",
                            Price = 85m
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 7,
                            CostPrice = 60m,
                            Description = "400 г. Томатний соус, моцарела, базилік",
                            IsAvailable = true,
                            Name = "Піца Маргарита",
                            Price = 190m
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 7,
                            CostPrice = 85m,
                            Description = "450 г. Моцарела, томатний соус, гостра салямі пепероні",
                            IsAvailable = true,
                            Name = "Піца Пепероні",
                            Price = 240m
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 7,
                            CostPrice = 110m,
                            Description = "420 г. Вершковий соус, моцарела, дорблю, пармезан, чеддер",
                            IsAvailable = true,
                            Name = "Піца Чотири Сири",
                            Price = 270m
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 7,
                            CostPrice = 120m,
                            Description = "500 г. Бекон, шинка, салямі, куряче філе, моцарела",
                            IsAvailable = true,
                            Name = "Піца М'ясна",
                            Price = 290m
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 7,
                            CostPrice = 80m,
                            Description = "460 г. Куряче філе, ананас, кукурудза, вершковий соус",
                            IsAvailable = true,
                            Name = "Піца Гавайська",
                            Price = 230m
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 7,
                            CostPrice = 95m,
                            Description = "480 г. Шинка, печериці, артишоки, оливки, моцарела",
                            IsAvailable = true,
                            Name = "Піца Капричоза",
                            Price = 260m
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 7,
                            CostPrice = 90m,
                            Description = "440 г. Печериці, білі гриби, трюфельна олія, вершковий соус",
                            IsAvailable = true,
                            Name = "Піца Грибна",
                            Price = 250m
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 7,
                            CostPrice = 115m,
                            Description = "430 г. Прошуто крудо, рукола, томати чері, пармезан",
                            IsAvailable = true,
                            Name = "Піца Прошуто",
                            Price = 285m
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 7,
                            CostPrice = 90m,
                            Description = "450 г. Гострий соус, салямі, перець халапеньйо",
                            IsAvailable = true,
                            Name = "Піца Дьявола",
                            Price = 245m
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 7,
                            CostPrice = 105m,
                            Description = "470 г. Куряче філе, бекон, айсберг, соус цезар, перепелині яйця",
                            IsAvailable = true,
                            Name = "Піца Цезар",
                            Price = 280m
                        });
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BonusUsed")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("TableNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("TipAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.LoyaltyTransaction", b =>
                {
                    b.HasOne("CoffeeShopLoyalty.Api.Models.Customer", "Customer")
                        .WithMany("LoyaltyTransactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShopLoyalty.Api.Models.Order", "Order")
                        .WithMany("LoyaltyTransactions")
                        .HasForeignKey("OrderId");

                    b.Navigation("Customer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.MenuItem", b =>
                {
                    b.HasOne("CoffeeShopLoyalty.Api.Models.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.Order", b =>
                {
                    b.HasOne("CoffeeShopLoyalty.Api.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.OrderItem", b =>
                {
                    b.HasOne("CoffeeShopLoyalty.Api.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShopLoyalty.Api.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.Customer", b =>
                {
                    b.Navigation("LoyaltyTransactions");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.Order", b =>
                {
                    b.Navigation("LoyaltyTransactions");

                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
