// <auto-generated />
using System;
using CoffeeShopLoyalty.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeeShopLoyalty.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260412200305_UpdateMenuWithTags")]
    partial class UpdateMenuWithTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Кава та чай"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Напої б/а"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Кондитерка"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Випічка"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Хліба"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Круасани та мафіни"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Піца"
                        });
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BonusBalance")
                        .HasColumnType("numeric");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasUsedReferral")
                        .HasColumnType("boolean");

                    b.Property<string>("LoyaltyLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ReferredByCustomerId")
                        .HasColumnType("integer");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.LoyaltyTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PointsAdded")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PointsDeducted")
                        .HasColumnType("numeric");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.ToTable("LoyaltyTransactions");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("ContainsGluten")
                        .HasColumnType("boolean");

                    b.Property<bool>("ContainsLactose")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSpicy")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("WeightOrVolume")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 15m,
                            Description = "Класична міцна кава",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Еспресо",
                            Price = 45m,
                            WeightOrVolume = "30 мл"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 16m,
                            Description = "Еспресо з додаванням гарячої води",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Американо",
                            Price = 50m,
                            WeightOrVolume = "150 мл"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ContainsGluten = false,
                            ContainsLactose = true,
                            CostPrice = 25m,
                            Description = "Еспресо зі збитим гарячим молоком",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Капучино",
                            Price = 65m,
                            WeightOrVolume = "250 мл"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ContainsGluten = false,
                            ContainsLactose = true,
                            CostPrice = 30m,
                            Description = "Багато молока та шот еспресо",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Лате",
                            Price = 75m,
                            WeightOrVolume = "350 мл"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            ContainsGluten = false,
                            ContainsLactose = true,
                            CostPrice = 35m,
                            Description = "Подвійне еспресо та трохи збитого молока",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Флет Вайт",
                            Price = 80m,
                            WeightOrVolume = "200 мл"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            ContainsGluten = false,
                            ContainsLactose = true,
                            CostPrice = 45m,
                            Description = "Кава на вершках з ванільним цукром",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Раф",
                            Price = 90m,
                            WeightOrVolume = "300 мл"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            ContainsGluten = false,
                            ContainsLactose = true,
                            CostPrice = 50m,
                            Description = "Японський зелений чай з молоком",
                            IsAvailable = true,
                            IsNew = true,
                            IsSpicy = false,
                            Name = "Матча Лате",
                            Price = 110m,
                            WeightOrVolume = "300 мл"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 10m,
                            Description = "Заварний листовий чай",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Чай чорний",
                            Price = 55m,
                            WeightOrVolume = "400 мл"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 10m,
                            Description = "Заварний листовий чай з жасмином",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Чай зелений",
                            Price = 55m,
                            WeightOrVolume = "400 мл"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            ContainsGluten = false,
                            ContainsLactose = true,
                            CostPrice = 25m,
                            Description = "Натуральне какао на молоці",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Какао",
                            Price = 70m,
                            WeightOrVolume = "300 мл"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 30m,
                            Description = "Лимон, м'ята, цукровий сироп, содова",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Лимонад Класичний",
                            Price = 85m,
                            WeightOrVolume = "400 мл"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 35m,
                            Description = "Лайм, свіжа м'ята, спрайт, лід",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Мохіто б/а",
                            Price = 95m,
                            WeightOrVolume = "400 мл"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            ContainsGluten = false,
                            ContainsLactose = true,
                            CostPrice = 32m,
                            Description = "Холодне молоко, еспресо, лід",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Айс Лате",
                            Price = 85m,
                            WeightOrVolume = "350 мл"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 40m,
                            Description = "Тонік, подвійне еспресо, лід, лимон",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Еспресо Тонік",
                            Price = 100m,
                            WeightOrVolume = "300 мл"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 60m,
                            Description = "100% свіжовичавлений сік",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Фреш Апельсиновий",
                            Price = 120m,
                            WeightOrVolume = "250 мл"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 65m,
                            Description = "100% свіжовичавлений сік",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Фреш Грейпфрутовий",
                            Price = 130m,
                            WeightOrVolume = "250 мл"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 25m,
                            Description = "Скляна пляшка",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Кока-Кола",
                            Price = 50m,
                            WeightOrVolume = "330 мл"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 18m,
                            Description = "Негазована / Газована",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Вода Моршинська",
                            Price = 40m,
                            WeightOrVolume = "500 мл"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 50m,
                            Description = "Ферментований напій (в асортименті)",
                            IsAvailable = true,
                            IsNew = true,
                            IsSpicy = false,
                            Name = "Комбуча",
                            Price = 90m,
                            WeightOrVolume = "330 мл"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            ContainsGluten = false,
                            ContainsLactose = true,
                            CostPrice = 45m,
                            Description = "Морозиво, молоко, збиті вершки",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Мілкшейк Ванільний",
                            Price = 110m,
                            WeightOrVolume = "400 мл"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 45m,
                            Description = "Класичний листковий торт з заварним кремом",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Торт Наполеон",
                            Price = 120m,
                            WeightOrVolume = "150 г"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 55m,
                            Description = "Вершковий сир, пісочна основа",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Чизкейк Нью-Йорк",
                            Price = 140m,
                            WeightOrVolume = "160 г"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 60m,
                            Description = "Савоярді, маскарпоне, кава",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Тірамісу",
                            Price = 135m,
                            WeightOrVolume = "150 г"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            ContainsGluten = false,
                            ContainsLactose = true,
                            CostPrice = 20m,
                            Description = "Мигдальне тістечко (різні смаки)",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Макарон",
                            Price = 55m,
                            WeightOrVolume = "30 г"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 25m,
                            Description = "Заварне тісто, крем пломбір",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Еклер Ванільний",
                            Price = 80m,
                            WeightOrVolume = "80 г"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 35m,
                            Description = "Шоколадний десерт з вологою серединкою",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Брауні",
                            Price = 95m,
                            WeightOrVolume = "120 г"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 18m,
                            Description = "Бісквітна крихта, какао, ром",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Тістечко Картопля",
                            Price = 65m,
                            WeightOrVolume = "90 г"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 40m,
                            Description = "Медові коржі зі сметанним кремом",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Медовик",
                            Price = 110m,
                            WeightOrVolume = "140 г"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            ContainsGluten = false,
                            ContainsLactose = true,
                            CostPrice = 35m,
                            Description = "Вершковий десерт з ягідним кюлі",
                            IsAvailable = true,
                            IsNew = true,
                            IsSpicy = false,
                            Name = "Панакота",
                            Price = 105m,
                            WeightOrVolume = "150 г"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 45m,
                            Description = "Пісочне тісто, заварний крем, сезонні ягоди",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Тарталетка Ягідна",
                            Price = 125m,
                            WeightOrVolume = "110 г"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 30m,
                            Description = "Булочка з корицею та крем-сиром",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Синнабон",
                            Price = 100m,
                            WeightOrVolume = "180 г"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            ContainsGluten = true,
                            ContainsLactose = false,
                            CostPrice = 15m,
                            Description = "Печений пиріжок зі свининою та яловичиною",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Пиріжок з м'ясом",
                            Price = 45m,
                            WeightOrVolume = "100 г"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            ContainsGluten = true,
                            ContainsLactose = false,
                            CostPrice = 12m,
                            Description = "Печений пиріжок з солодкою вишнею",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Пиріжок з вишнею",
                            Price = 40m,
                            WeightOrVolume = "100 г"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 20m,
                            Description = "Молочна сосиска у листковому тісті",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Сосиска в тісті",
                            Price = 55m,
                            WeightOrVolume = "120 г"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 30m,
                            Description = "Листкове тісто, сир сулугуні",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Хачапурі з сиром",
                            Price = 85m,
                            WeightOrVolume = "150 г"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 60m,
                            Description = "Відкритий пиріг з лососем та шпинатом",
                            IsAvailable = true,
                            IsNew = true,
                            IsSpicy = false,
                            Name = "Кіш з лососем",
                            Price = 150m,
                            WeightOrVolume = "200 г"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            ContainsGluten = true,
                            ContainsLactose = false,
                            CostPrice = 20m,
                            Description = "Листкове тісто з яблуком та корицею",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Слойка з яблуком",
                            Price = 60m,
                            WeightOrVolume = "120 г"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 22m,
                            Description = "Заварний крем та родзинки",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Равлик з родзинками",
                            Price = 65m,
                            WeightOrVolume = "110 г"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            ContainsGluten = true,
                            ContainsLactose = false,
                            CostPrice = 15m,
                            Description = "Дріжджове тісто, багато маку",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Булочка з маком",
                            Price = 50m,
                            WeightOrVolume = "130 г"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 18m,
                            Description = "Класична ватрушка з домашнім сиром",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Ватрушка з сиром",
                            Price = 55m,
                            WeightOrVolume = "120 г"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 5,
                            ContainsGluten = true,
                            ContainsLactose = false,
                            CostPrice = 15m,
                            Description = "Хрустка скоринка, пористий м'якуш",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Багет Французький",
                            Price = 60m,
                            WeightOrVolume = "300 г"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 5,
                            ContainsGluten = true,
                            ContainsLactose = false,
                            CostPrice = 18m,
                            Description = "Класичний італійський хліб на заквасці",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Чіабата",
                            Price = 70m,
                            WeightOrVolume = "250 г"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 5,
                            ContainsGluten = true,
                            ContainsLactose = false,
                            CostPrice = 20m,
                            Description = "Темний хліб на житній заквасці",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Хліб Житній",
                            Price = 65m,
                            WeightOrVolume = "400 г"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            ContainsGluten = true,
                            ContainsLactose = false,
                            CostPrice = 22m,
                            Description = "З кмином та коріандром",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Бородінський",
                            Price = 75m,
                            WeightOrVolume = "350 г"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 5,
                            ContainsGluten = true,
                            ContainsLactose = false,
                            CostPrice = 25m,
                            Description = "З додаванням гречаного борошна",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Гречаний хліб",
                            Price = 80m,
                            WeightOrVolume = "350 г"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 5,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 15m,
                            Description = "Ідеально рівний для сендвічів",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Тостовий хліб",
                            Price = 55m,
                            WeightOrVolume = "450 г"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 5,
                            ContainsGluten = true,
                            ContainsLactose = false,
                            CostPrice = 12m,
                            Description = "Класичний білий батон",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Батон Нарізний",
                            Price = 45m,
                            WeightOrVolume = "400 г"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            ContainsGluten = true,
                            ContainsLactose = false,
                            CostPrice = 30m,
                            Description = "Італійський корж з чері та розмарином",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Фокача з томатами",
                            Price = 95m,
                            WeightOrVolume = "300 г"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 8m,
                            Description = "Бріош з кунжутом",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Булочка для бургера",
                            Price = 25m,
                            WeightOrVolume = "90 г"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 45m,
                            Description = "На основі рисового та кукурудзяного борошна",
                            IsAvailable = true,
                            IsNew = true,
                            IsSpicy = false,
                            Name = "Хліб безглютеновий",
                            Price = 120m,
                            WeightOrVolume = "300 г"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 6,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 25m,
                            Description = "Справжній вершковий круасан на маслі 82%",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Круасан Класичний",
                            Price = 70m,
                            WeightOrVolume = "80 г"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 6,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 35m,
                            Description = "З начинкою з бельгійського шоколаду",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Круасан Шоколадний",
                            Price = 95m,
                            WeightOrVolume = "110 г"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 6,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 45m,
                            Description = "З франжипаном та мигдальними пластівцями",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Круасан з мигдалем",
                            Price = 120m,
                            WeightOrVolume = "130 г"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 6,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 55m,
                            Description = "З фісташковим кремом",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Круасан Фісташковий",
                            Price = 135m,
                            WeightOrVolume = "120 г"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 6,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 50m,
                            Description = "Ситний круасан з сиром чеддер та шинкою",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Круасан Шинка/Сир",
                            Price = 140m,
                            WeightOrVolume = "160 г"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 6,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 80m,
                            Description = "Слабосолений лосось, крем-сир, рукола",
                            IsAvailable = true,
                            IsNew = true,
                            IsSpicy = false,
                            Name = "Круасан з лососем",
                            Price = 180m,
                            WeightOrVolume = "170 г"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 6,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 25m,
                            Description = "Вологий кекс з шматочками шоколаду",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Мафін Шоколадний",
                            Price = 75m,
                            WeightOrVolume = "110 г"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 6,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 28m,
                            Description = "Зі свіжою лохиною та чорницею",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Мафін Чорничний",
                            Price = 80m,
                            WeightOrVolume = "110 г"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 6,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 20m,
                            Description = "Класичний кекс з ваніллю",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Мафін Ванільний",
                            Price = 65m,
                            WeightOrVolume = "110 г"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 6,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 30m,
                            Description = "З тягучою солоною карамеллю всередині",
                            IsAvailable = true,
                            IsNew = true,
                            IsSpicy = false,
                            Name = "Мафін Солона Карамель",
                            Price = 85m,
                            WeightOrVolume = "120 г"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 7,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 60m,
                            Description = "Томатний соус, моцарела, базилік",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Піца Маргарита",
                            Price = 190m,
                            WeightOrVolume = "400 г"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 7,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 85m,
                            Description = "Моцарела, томатний соус, гостра салямі пепероні",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = true,
                            Name = "Піца Пепероні",
                            Price = 240m,
                            WeightOrVolume = "450 г"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 7,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 110m,
                            Description = "Вершковий соус, моцарела, дорблю, пармезан, чеддер",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Піца Чотири Сири",
                            Price = 270m,
                            WeightOrVolume = "420 г"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 7,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 120m,
                            Description = "Бекон, шинка, салямі, куряче філе, моцарела",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Піца М'ясна",
                            Price = 290m,
                            WeightOrVolume = "500 г"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 7,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 80m,
                            Description = "Куряче філе, ананас, кукурудза, вершковий соус",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Піца Гавайська",
                            Price = 230m,
                            WeightOrVolume = "460 г"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 7,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 95m,
                            Description = "Шинка, печериці, артишоки, оливки, моцарела",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Піца Капричоза",
                            Price = 260m,
                            WeightOrVolume = "480 г"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 7,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 90m,
                            Description = "Печериці, білі гриби, трюфельна олія, вершковий соус",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Піца Грибна",
                            Price = 250m,
                            WeightOrVolume = "440 г"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 7,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 115m,
                            Description = "Прошуто крудо, рукола, томати чері, пармезан",
                            IsAvailable = true,
                            IsNew = true,
                            IsSpicy = false,
                            Name = "Піца Прошуто",
                            Price = 285m,
                            WeightOrVolume = "430 г"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 7,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 90m,
                            Description = "Гострий соус, салямі, перець халапеньйо",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = true,
                            Name = "Піца Дьявола",
                            Price = 245m,
                            WeightOrVolume = "450 г"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 7,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 105m,
                            Description = "Куряче філе, бекон, айсберг, соус цезар, перепелині яйця",
                            IsAvailable = true,
                            IsNew = true,
                            IsSpicy = false,
                            Name = "Піца Цезар",
                            Price = 280m,
                            WeightOrVolume = "470 г"
                        });
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BonusUsed")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("TableNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("TipAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.LoyaltyTransaction", b =>
                {
                    b.HasOne("CoffeeShopLoyalty.Api.Models.Customer", "Customer")
                        .WithMany("LoyaltyTransactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShopLoyalty.Api.Models.Order", "Order")
                        .WithMany("LoyaltyTransactions")
                        .HasForeignKey("OrderId");

                    b.Navigation("Customer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.MenuItem", b =>
                {
                    b.HasOne("CoffeeShopLoyalty.Api.Models.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.Order", b =>
                {
                    b.HasOne("CoffeeShopLoyalty.Api.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.OrderItem", b =>
                {
                    b.HasOne("CoffeeShopLoyalty.Api.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShopLoyalty.Api.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.Customer", b =>
                {
                    b.Navigation("LoyaltyTransactions");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.Order", b =>
                {
                    b.Navigation("LoyaltyTransactions");

                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
