// <auto-generated />
using System;
using CoffeeShopLoyalty.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeeShopLoyalty.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Кава та чай"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Напої б/а"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Кондитерка"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Випічка"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Хліба"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Круасани та мафіни"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Піца"
                        });
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BonusBalance")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasUsedReferral")
                        .HasColumnType("boolean");

                    b.Property<string>("LoyaltyLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ReferredByCustomerId")
                        .HasColumnType("integer");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.CustomerMenuItemLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("CustomerId", "MenuItemId")
                        .IsUnique();

                    b.ToTable("CustomerMenuItemLikes");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.LoyaltyTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PointsAdded")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PointsDeducted")
                        .HasColumnType("numeric");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.ToTable("LoyaltyTransactions");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("ContainsGluten")
                        .HasColumnType("boolean");

                    b.Property<bool>("ContainsLactose")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSpicy")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalLikes")
                        .HasColumnType("integer");

                    b.Property<string>("WeightOrVolume")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 15m,
                            Description = "Класична міцна кава",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775978213/CoffeShopAPI/iufii4r4uvoauk8lktfh.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Еспресо",
                            Price = 45m,
                            TotalLikes = 52,
                            WeightOrVolume = "30 мл"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 16m,
                            Description = "Еспресо з додаванням гарячої води",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775801274/f7bdko5pygqo5mudbt8x.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Американо",
                            Price = 50m,
                            TotalLikes = 40,
                            WeightOrVolume = "150 мл"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ContainsGluten = false,
                            ContainsLactose = true,
                            CostPrice = 25m,
                            Description = "Еспресо зі збитим гарячим молоком",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775978168/CoffeShopAPI/ra3gh8thr9y0plt2yko8.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Капучино",
                            Price = 65m,
                            TotalLikes = 110,
                            WeightOrVolume = "250 мл"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ContainsGluten = false,
                            ContainsLactose = true,
                            CostPrice = 30m,
                            Description = "Багато молока та шот еспресо",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775978187/CoffeShopAPI/ldbwnuhhupomrmmbyvm1.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Лате",
                            Price = 75m,
                            TotalLikes = 135,
                            WeightOrVolume = "350 мл"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            ContainsGluten = false,
                            ContainsLactose = true,
                            CostPrice = 35m,
                            Description = "Подвійне еспресо та трохи збитого молока",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775978260/CoffeShopAPI/m2wruhspxrr9z4qzfusg.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Флет Вайт",
                            Price = 80m,
                            TotalLikes = 75,
                            WeightOrVolume = "200 мл"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            ContainsGluten = false,
                            ContainsLactose = true,
                            CostPrice = 45m,
                            Description = "Кава на вершках з ванільним цукром",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775978155/CoffeShopAPI/xlcqeqzs56nuj6verukk.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Раф",
                            Price = 90m,
                            TotalLikes = 98,
                            WeightOrVolume = "300 мл"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            ContainsGluten = false,
                            ContainsLactose = true,
                            CostPrice = 50m,
                            Description = "Японський зелений чай з молоком",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775978286/CoffeShopAPI/p5giakxug8wasxz7x9mt.png",
                            IsAvailable = true,
                            IsNew = true,
                            IsSpicy = false,
                            Name = "Матча Лате",
                            Price = 110m,
                            TotalLikes = 120,
                            WeightOrVolume = "300 мл"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 10m,
                            Description = "Заварний листовий чай",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775978314/CoffeShopAPI/hucvamrz9bplemcgzdg9.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Чай чорний",
                            Price = 55m,
                            TotalLikes = 25,
                            WeightOrVolume = "400 мл"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 10m,
                            Description = "Заварний листовий чай з жасмином",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775978340/CoffeShopAPI/bnvaf1d53v1d5ehw6p79.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Чай зелений",
                            Price = 55m,
                            TotalLikes = 20,
                            WeightOrVolume = "400 мл"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            ContainsGluten = false,
                            ContainsLactose = true,
                            CostPrice = 25m,
                            Description = "Натуральне какао на молоці",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775978471/CoffeShopAPI/fholnuley1aaa9by6ivp.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Какао",
                            Price = 70m,
                            TotalLikes = 45,
                            WeightOrVolume = "300 мл"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 30m,
                            Description = "Лимон, м'ята, цукровий сироп, содова",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775978493/CoffeShopAPI/fygmasffccvriaayenx3.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Лимонад Класичний",
                            Price = 85m,
                            TotalLikes = 60,
                            WeightOrVolume = "400 мл"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 35m,
                            Description = "Лайм, свіжа м'ята, спрайт, лід",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775978516/CoffeShopAPI/rdwhiposgk2ngnhjbnsb.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Мохіто б/а",
                            Price = 95m,
                            TotalLikes = 58,
                            WeightOrVolume = "400 мл"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            ContainsGluten = false,
                            ContainsLactose = true,
                            CostPrice = 32m,
                            Description = "Холодне молоко, еспресо, лід",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775978563/CoffeShopAPI/eawyw6gwmvwibi2clwlw.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Айс Лате",
                            Price = 85m,
                            TotalLikes = 92,
                            WeightOrVolume = "350 мл"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 40m,
                            Description = "Тонік, подвійне еспресо, лід, лимон",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775978602/CoffeShopAPI/kcrcg09euwl7squcn525.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Еспресо Тонік",
                            Price = 100m,
                            TotalLikes = 65,
                            WeightOrVolume = "300 мл"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 60m,
                            Description = "100% свіжовичавлений сік",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775978616/CoffeShopAPI/yblq5lxfucxp4khyeegs.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Фреш Апельсиновий",
                            Price = 120m,
                            TotalLikes = 44,
                            WeightOrVolume = "250 мл"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 65m,
                            Description = "100% свіжовичавлений сік",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775978638/CoffeShopAPI/huh6g7bs5lumsctzxxgj.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Фреш Грейпфрутовий",
                            Price = 130m,
                            TotalLikes = 42,
                            WeightOrVolume = "250 мл"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 25m,
                            Description = "Скляна пляшка",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775978663/CoffeShopAPI/jr5qesmncf87uwok5j5s.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Кока-Кола",
                            Price = 50m,
                            TotalLikes = 88,
                            WeightOrVolume = "330 мл"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 18m,
                            Description = "Негазована / Газована",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775978830/CoffeShopAPI/jorroz1xeimqderm3obi.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Вода Моршинська",
                            Price = 40m,
                            TotalLikes = 70,
                            WeightOrVolume = "500 мл"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 50m,
                            Description = "Ферментований напій (в асортименті)",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775978879/CoffeShopAPI/aueo3sg6gbogcqinmt23.png",
                            IsAvailable = true,
                            IsNew = true,
                            IsSpicy = false,
                            Name = "Комбуча",
                            Price = 90m,
                            TotalLikes = 55,
                            WeightOrVolume = "330 мл"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            ContainsGluten = false,
                            ContainsLactose = true,
                            CostPrice = 45m,
                            Description = "Морозиво, молоко, збиті вершки",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775978891/CoffeShopAPI/dmt2nslnivrjqjhudf2i.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Мілкшейк Ванільний",
                            Price = 110m,
                            TotalLikes = 66,
                            WeightOrVolume = "400 мл"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 45m,
                            Description = "Класичний листковий торт з заварним кремом",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775978999/CoffeShopAPI/uzl8x6pbxm27834s98gv.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Торт Наполеон",
                            Price = 120m,
                            TotalLikes = 105,
                            WeightOrVolume = "150 г"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 55m,
                            Description = "Вершковий сир, пісочна основа",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775979021/CoffeShopAPI/tannhyab44hcue2rh4bs.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Чизкейк Нью-Йорк",
                            Price = 140m,
                            TotalLikes = 88,
                            WeightOrVolume = "160 г"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 60m,
                            Description = "Савоярді, маскарпоне, кава",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775979034/CoffeShopAPI/kdbpxlyi7dvwvjg9bfhg.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Тірамісу",
                            Price = 135m,
                            TotalLikes = 94,
                            WeightOrVolume = "150 г"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            ContainsGluten = false,
                            ContainsLactose = true,
                            CostPrice = 20m,
                            Description = "Мигдальне тістечко (різні смаки)",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775979089/CoffeShopAPI/yxvxixwix4ptl9ipvlas.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Макарон",
                            Price = 55m,
                            TotalLikes = 130,
                            WeightOrVolume = "30 г"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 25m,
                            Description = "Заварне тісто, крем пломбір",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775979103/CoffeShopAPI/duwu16xkdo5b5utkpx2m.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Еклер Ванільний",
                            Price = 80m,
                            TotalLikes = 77,
                            WeightOrVolume = "80 г"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 35m,
                            Description = "Шоколадний десерт з вологою серединкою",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775979113/CoffeShopAPI/gabfsk3nprbewgv8gd8t.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Брауні",
                            Price = 95m,
                            TotalLikes = 85,
                            WeightOrVolume = "120 г"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 18m,
                            Description = "Бісквітна крихта, какао, ром",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775979126/CoffeShopAPI/kcwd6vp4va0ldaknwqww.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Тістечко Картопля",
                            Price = 65m,
                            TotalLikes = 60,
                            WeightOrVolume = "90 г"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 40m,
                            Description = "Медові коржі зі сметанним кремом",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775979142/CoffeShopAPI/cevoiex66ktems0mrocb.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Медовик",
                            Price = 110m,
                            TotalLikes = 74,
                            WeightOrVolume = "140 г"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            ContainsGluten = false,
                            ContainsLactose = true,
                            CostPrice = 35m,
                            Description = "Вершковий десерт з ягідним кюлі",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775979164/CoffeShopAPI/cgb4n1osgs82rnj5wnyk.png",
                            IsAvailable = true,
                            IsNew = true,
                            IsSpicy = false,
                            Name = "Панакота",
                            Price = 105m,
                            TotalLikes = 59,
                            WeightOrVolume = "150 г"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 45m,
                            Description = "Пісочне тісто, заварний крем, сезонні ягоди",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775979184/CoffeShopAPI/adkusmw9gxqxi7y8gxih.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Тарталетка Ягідна",
                            Price = 125m,
                            TotalLikes = 82,
                            WeightOrVolume = "110 г"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 30m,
                            Description = "Булочка з корицею та крем-сиром",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775979673/CoffeShopAPI/xiivscv6ncxvrvmsytmm.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Синнабон",
                            Price = 100m,
                            TotalLikes = 148,
                            WeightOrVolume = "180 г"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            ContainsGluten = true,
                            ContainsLactose = false,
                            CostPrice = 15m,
                            Description = "Печений пиріжок зі свининою та яловичиною",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775979693/CoffeShopAPI/vaubw4rasmxxjmizbetk.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Пиріжок з м'ясом",
                            Price = 45m,
                            TotalLikes = 40,
                            WeightOrVolume = "100 г"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            ContainsGluten = true,
                            ContainsLactose = false,
                            CostPrice = 12m,
                            Description = "Печений пиріжок з солодкою вишнею",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775979712/CoffeShopAPI/pr1yb9dlsm6rtozswauy.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Пиріжок з вишнею",
                            Price = 40m,
                            TotalLikes = 43,
                            WeightOrVolume = "100 г"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 20m,
                            Description = "Молочна сосиска у листковому тісті",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775979735/CoffeShopAPI/kwdotxxohu0cbqn1zqao.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Сосиска в тісті",
                            Price = 55m,
                            TotalLikes = 55,
                            WeightOrVolume = "120 г"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 30m,
                            Description = "Листкове тісто, сир сулугуні",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775979771/CoffeShopAPI/rfod5yv7bfw3ky39bheh.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Хачапурі з сиром",
                            Price = 85m,
                            TotalLikes = 67,
                            WeightOrVolume = "150 г"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 60m,
                            Description = "Відкритий пиріг з лососем та шпинатом",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775979795/CoffeShopAPI/gqxjlmlqvmus8ii8ju3m.png",
                            IsAvailable = true,
                            IsNew = true,
                            IsSpicy = false,
                            Name = "Кіш з лососем",
                            Price = 150m,
                            TotalLikes = 61,
                            WeightOrVolume = "200 г"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            ContainsGluten = true,
                            ContainsLactose = false,
                            CostPrice = 20m,
                            Description = "Листкове тісто з яблуком та корицею",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775979818/CoffeShopAPI/gqo7ldgmyriiy98nuibo.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Слойка з яблуком",
                            Price = 60m,
                            TotalLikes = 42,
                            WeightOrVolume = "120 г"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 22m,
                            Description = "Заварний крем та родзинки",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775979840/CoffeShopAPI/wjftkpn8hlbzk12fxqcw.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Равлик з родзинками",
                            Price = 65m,
                            TotalLikes = 44,
                            WeightOrVolume = "110 г"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            ContainsGluten = true,
                            ContainsLactose = false,
                            CostPrice = 15m,
                            Description = "Дріжджове тісто, багато маку",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775979863/CoffeShopAPI/giwzoieygvsgrdyccmvp.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Булочка з маком",
                            Price = 50m,
                            TotalLikes = 33,
                            WeightOrVolume = "130 г"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 18m,
                            Description = "Класична ватрушка з домашнім сиром",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1775979877/CoffeShopAPI/v13mwmygiathv81p5q6f.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Ватрушка з сиром",
                            Price = 55m,
                            TotalLikes = 36,
                            WeightOrVolume = "120 г"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 5,
                            ContainsGluten = true,
                            ContainsLactose = false,
                            CostPrice = 15m,
                            Description = "Хрустка скоринка, пористий м'якуш",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776104946/CoffeShopAPI/kz4qmzayweaykrs7ekun.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Багет Французький",
                            Price = 60m,
                            TotalLikes = 50,
                            WeightOrVolume = "300 г"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 5,
                            ContainsGluten = true,
                            ContainsLactose = false,
                            CostPrice = 18m,
                            Description = "Класичний італійський хліб на заквасці",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776104968/CoffeShopAPI/jfbfyeblxjefaytugui8.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Чіабата",
                            Price = 70m,
                            TotalLikes = 65,
                            WeightOrVolume = "250 г"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 5,
                            ContainsGluten = true,
                            ContainsLactose = false,
                            CostPrice = 20m,
                            Description = "Темний хліб на житній заквасці",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776104989/CoffeShopAPI/zf5tydllliw8fxbu8aai.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Хліб Житній",
                            Price = 65m,
                            TotalLikes = 30,
                            WeightOrVolume = "400 г"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            ContainsGluten = true,
                            ContainsLactose = false,
                            CostPrice = 22m,
                            Description = "З кмином та коріандром",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105008/CoffeShopAPI/x3tv8nbu1kqbiwkhsngf.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Бородінський",
                            Price = 75m,
                            TotalLikes = 35,
                            WeightOrVolume = "350 г"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 5,
                            ContainsGluten = true,
                            ContainsLactose = false,
                            CostPrice = 25m,
                            Description = "З додаванням гречаного борошна",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105053/CoffeShopAPI/vmtiqnq21ezeojb0dka7.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Гречаний хліб",
                            Price = 80m,
                            TotalLikes = 32,
                            WeightOrVolume = "350 г"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 5,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 15m,
                            Description = "Ідеально рівний для сендвічів",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105075/CoffeShopAPI/qjjwn0stwzh0zfb0htly.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Тостовий хліб",
                            Price = 55m,
                            TotalLikes = 31,
                            WeightOrVolume = "450 г"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 5,
                            ContainsGluten = true,
                            ContainsLactose = false,
                            CostPrice = 12m,
                            Description = "Класичний білий батон",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105099/CoffeShopAPI/tbfmuxtaqkn2ol9hu7ko.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Батон Нарізний",
                            Price = 45m,
                            TotalLikes = 30,
                            WeightOrVolume = "400 г"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            ContainsGluten = true,
                            ContainsLactose = false,
                            CostPrice = 30m,
                            Description = "Італійський корж з чері та розмарином",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105131/CoffeShopAPI/nz045qrv7qm2i1xfwl4x.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Фокача з томатами",
                            Price = 95m,
                            TotalLikes = 55,
                            WeightOrVolume = "300 г"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 8m,
                            Description = "Бріош з кунжутом",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105152/CoffeShopAPI/gxdnfx6xj0ix0ohw57qm.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Булочка для бургера",
                            Price = 25m,
                            TotalLikes = 25,
                            WeightOrVolume = "90 г"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            ContainsGluten = false,
                            ContainsLactose = false,
                            CostPrice = 45m,
                            Description = "На основі рисового та кукурудзяного борошна",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105175/CoffeShopAPI/jcd6doncvfegz9tpn7dj.png",
                            IsAvailable = true,
                            IsNew = true,
                            IsSpicy = false,
                            Name = "Хліб безглютеновий",
                            Price = 120m,
                            TotalLikes = 39,
                            WeightOrVolume = "300 г"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 6,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 25m,
                            Description = "Справжній вершковий круасан на маслі 82%",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105213/CoffeShopAPI/vgwjec1kxv7d3r9woffn.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Круасан Класичний",
                            Price = 70m,
                            TotalLikes = 135,
                            WeightOrVolume = "80 г"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 6,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 35m,
                            Description = "З начинкою з бельгійського шоколаду",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105241/CoffeShopAPI/iiwbu7gtikpl7xzkuqfx.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Круасан Шоколадний",
                            Price = 95m,
                            TotalLikes = 148,
                            WeightOrVolume = "110 г"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 6,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 45m,
                            Description = "З франжипаном та мигдальними пластівцями",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105261/CoffeShopAPI/jd8lh3kfsdnxrv6lm2hn.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Круасан з мигдалем",
                            Price = 120m,
                            TotalLikes = 122,
                            WeightOrVolume = "130 г"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 6,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 55m,
                            Description = "З фісташковим кремом",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105285/CoffeShopAPI/d98tnmj2cntsmpqfsrce.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Круасан Фісташковий",
                            Price = 135m,
                            TotalLikes = 148,
                            WeightOrVolume = "120 г"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 6,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 50m,
                            Description = "Ситний круасан з сиром чеддер та шинкою",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105311/CoffeShopAPI/tpf4jtqbpluuv7a58nvg.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Круасан Шинка/Сир",
                            Price = 140m,
                            TotalLikes = 111,
                            WeightOrVolume = "160 г"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 6,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 80m,
                            Description = "Слабосолений лосось, крем-сир, рукола",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105322/CoffeShopAPI/ux49b3gcbjajtwor3elt.png",
                            IsAvailable = true,
                            IsNew = true,
                            IsSpicy = false,
                            Name = "Круасан з лососем",
                            Price = 180m,
                            TotalLikes = 105,
                            WeightOrVolume = "170 г"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 6,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 25m,
                            Description = "Вологий кекс з шматочками шоколаду",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105359/CoffeShopAPI/usbkiktiqxtwyu3uvxcl.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Мафін Шоколадний",
                            Price = 75m,
                            TotalLikes = 77,
                            WeightOrVolume = "110 г"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 6,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 28m,
                            Description = "Зі свіжою лохиною та чорницею",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105382/CoffeShopAPI/ycpzhglvcmwjht1vv5zt.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Мафін Чорничний",
                            Price = 80m,
                            TotalLikes = 82,
                            WeightOrVolume = "110 г"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 6,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 20m,
                            Description = "Класичний кекс з ваніллю",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105402/CoffeShopAPI/wiimhghikyta1kwysauu.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Мафін Ванільний",
                            Price = 65m,
                            TotalLikes = 55,
                            WeightOrVolume = "110 г"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 6,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 30m,
                            Description = "З тягучою солоною карамеллю всередині",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105432/CoffeShopAPI/urmjljzlsxandakymaad.png",
                            IsAvailable = true,
                            IsNew = true,
                            IsSpicy = false,
                            Name = "Мафін Солона Карамель",
                            Price = 85m,
                            TotalLikes = 91,
                            WeightOrVolume = "120 г"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 7,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 60m,
                            Description = "Томатний соус, моцарела, базилік",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105469/CoffeShopAPI/js8eyyxplmtaqjfkcd5w.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Піца Маргарита",
                            Price = 190m,
                            TotalLikes = 160,
                            WeightOrVolume = "400 г"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 7,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 85m,
                            Description = "Моцарела, томатний соус, гостра салямі пепероні",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105492/CoffeShopAPI/tpf3gqhp3iida1zfslqc.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = true,
                            Name = "Піца Пепероні",
                            Price = 240m,
                            TotalLikes = 195,
                            WeightOrVolume = "450 г"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 7,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 110m,
                            Description = "Вершковий соус, моцарела, дорблю, пармезан, чеддер",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105510/CoffeShopAPI/iqvvswglipacnzbyemb0.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Піца Чотири Сири",
                            Price = 270m,
                            TotalLikes = 188,
                            WeightOrVolume = "420 г"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 7,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 120m,
                            Description = "Бекон, шинка, салямі, куряче філе, моцарела",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105568/CoffeShopAPI/lpae6kgsk88ny61zdhl3.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Піца М'ясна",
                            Price = 290m,
                            TotalLikes = 175,
                            WeightOrVolume = "500 г"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 7,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 80m,
                            Description = "Куряче філе, ананас, кукурудза, вершковий соус",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105632/CoffeShopAPI/mzaxatgm2csc34psub8t.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Піца Гавайська",
                            Price = 230m,
                            TotalLikes = 140,
                            WeightOrVolume = "460 г"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 7,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 95m,
                            Description = "Шинка, печериці, артишоки, оливки, моцарела",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105656/CoffeShopAPI/cq9mc39hgbeyd3sztt51.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Піца Капричоза",
                            Price = 260m,
                            TotalLikes = 155,
                            WeightOrVolume = "480 г"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 7,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 90m,
                            Description = "Печериці, білі гриби, трюфельна олія, вершковий соус",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105688/CoffeShopAPI/bgso5zebobqrkbctwhaa.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = false,
                            Name = "Піца Грибна",
                            Price = 250m,
                            TotalLikes = 144,
                            WeightOrVolume = "440 г"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 7,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 115m,
                            Description = "Прошуто крудо, рукола, томати чері, пармезан",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105715/CoffeShopAPI/bj1jll2iwkqh1zickc9i.png",
                            IsAvailable = true,
                            IsNew = true,
                            IsSpicy = false,
                            Name = "Піца Прошуто",
                            Price = 285m,
                            TotalLikes = 139,
                            WeightOrVolume = "430 г"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 7,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 90m,
                            Description = "Гострий соус, салямі, перець халапеньйо",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105727/CoffeShopAPI/k0robmt0j6bhnmin0u4y.png",
                            IsAvailable = true,
                            IsNew = false,
                            IsSpicy = true,
                            Name = "Піца Дьявола",
                            Price = 245m,
                            TotalLikes = 210,
                            WeightOrVolume = "450 г"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 7,
                            ContainsGluten = true,
                            ContainsLactose = true,
                            CostPrice = 105m,
                            Description = "Куряче філе, бекон, айсберг, соус цезар, перепелині яйця",
                            ImageUrl = "https://res.cloudinary.com/dojoliqlm/image/upload/v1776105749/CoffeShopAPI/yrpzqjsxewxmurnxfaix.png",
                            IsAvailable = true,
                            IsNew = true,
                            IsSpicy = false,
                            Name = "Піца Цезар",
                            Price = 280m,
                            TotalLikes = 168,
                            WeightOrVolume = "470 г"
                        });
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BonusUsed")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("TableNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("TipAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromoType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.CustomerMenuItemLike", b =>
                {
                    b.HasOne("CoffeeShopLoyalty.Api.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShopLoyalty.Api.Models.MenuItem", "MenuItem")
                        .WithMany("CustomerLikes")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.LoyaltyTransaction", b =>
                {
                    b.HasOne("CoffeeShopLoyalty.Api.Models.Customer", "Customer")
                        .WithMany("LoyaltyTransactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShopLoyalty.Api.Models.Order", "Order")
                        .WithMany("LoyaltyTransactions")
                        .HasForeignKey("OrderId");

                    b.Navigation("Customer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.MenuItem", b =>
                {
                    b.HasOne("CoffeeShopLoyalty.Api.Models.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.Order", b =>
                {
                    b.HasOne("CoffeeShopLoyalty.Api.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.OrderItem", b =>
                {
                    b.HasOne("CoffeeShopLoyalty.Api.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShopLoyalty.Api.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.Customer", b =>
                {
                    b.Navigation("LoyaltyTransactions");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.MenuItem", b =>
                {
                    b.Navigation("CustomerLikes");
                });

            modelBuilder.Entity("CoffeeShopLoyalty.Api.Models.Order", b =>
                {
                    b.Navigation("LoyaltyTransactions");

                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
